Исправления на главной странице
CPP-KT/course pull request #5
Opened 2023-09-25 13:21 UTC by ErzherzogDX

1. Добавлена табличка с примером работы формулы расчета баллов за ДЗ.
2. Исправлены некоторые пунктуационные и грамматические ошибки.
3. Уточнена информация по разбалловке.

2023-09-26 14:49 UTC, dedlocc requested changes

2023-09-26 14:49 UTC, dedlocc commented on src/points.md
> +* Оценка -- это ваши суммарные баллы за практические, домашние задания и экзамен (а так же -- бонусы).
так же -> также

2023-09-26 14:49 UTC, dedlocc commented on src/points.md
> +* Без успешной сдачи экзамена вы не можете получить оценку выше FX, то есть:
может просто "положительную оценку"?

2023-09-26 14:49 UTC, dedlocc commented on src/points.md
> +	* __Домашние задания__ - 66 баллов. Задания, которые будут выдавать в течение семестра. Для каждой будет отдельный дедлайн, за просрочку которого будет штраф на итоговое количество баллов.
можно подумать, что речь идёт об итоговом кол-ве баллов за весь курс, лучше написать яснее

2023-09-26 14:49 UTC, dedlocc commented on src/points.md
> +	* __Экзамен__ - 20 баллов. Состоит из практической и теоретической части, каждая стоит по 10 баллов. В практической вы за несколько часов пишете задание, которое оценит преподаватель, а в теоретичес
давай заодно поправим "части" на "частей"

2023-09-26 14:49 UTC, dedlocc commented on src/points.md
> +	* __Экзамен__ - 20 баллов. Состоит из практической и теоретической части, каждая стоит по 10 баллов. В практической вы за несколько часов пишете задание, которое оценит преподаватель, а в теоретичес
тут тире одинарное, а выше двойное было, давай как-нибудь однообразно сделаем

2023-09-26 14:49 UTC, dedlocc commented on src/points.md
> +	* __Экзамен__ - 20 баллов. Состоит из практической и теоретической части, каждая стоит по 10 баллов. В практической вы за несколько часов пишете задание, которое оценит преподаватель, а в теоретичес
тоже можно "положительную оценку"

2023-09-26 14:49 UTC, dedlocc commented on src/points.md
> +	* __Экзамен__ - 20 баллов. Состоит из практической и теоретической части, каждая стоит по 10 баллов. В практической вы за несколько часов пишете задание, которое оценит преподаватель, а в теоретичес
мб лучше скобки перенести в конец?

2023-09-26 14:49 UTC, dedlocc commented on src/points.md
> +| +      | 01.09, 00:00 | Дедлайн просрочен на 124 дня      | 11.008 |
предлагаю рассмотреть какой-нибудь более искусственный пример, чтоб в частности не пришлось его менять, если вдруг список заданий изменится

2023-09-26 14:49 UTC, dedlocc commented on src/points.md
> +| +      | 01.09, 00:00 | Дедлайн просрочен на 124 дня      | 11.008 |
[note] возможно более репрезентативно будет рассмотреть в последней строчке что-нибудь отличное от `+`?

2023-09-26 14:49 UTC, dedlocc commented on src/points.md
> +| +      | 31.04, 23:59 | Дедлайн соблюден, недочетов нет   | 17.600 |
соблюден -> соблюдён
недочетов -> недочётов

2023-09-26 14:49 UTC, dedlocc commented on src/points.md
> +По [этой ссылке](https://www.wolframalpha.com/input?i=1*17.6*%280.6+%2B+0.4%2F%281%2B0.35*ceiling%28x%2F3%29%29%29) вы можете сами покрутить эту формулу в WolframAlpha.
думаю, это лишнее

2023-09-26 16:16 UTC, ErzherzogDX commented on src/points.md
> +* Оценка -- это ваши суммарные баллы за практические, домашние задания и экзамен (а так же -- бонусы).
ок

2023-09-26 16:17 UTC, ErzherzogDX commented on src/points.md
> +* Без успешной сдачи экзамена вы не можете получить оценку выше FX, то есть:
мне кажется, что это можно слишком неоднозначно трактовать - условно, для одних людей положительная оценка - это то что выше 60 баллов, а для других - все что больше четверки

2023-09-26 16:17 UTC, ErzherzogDX commented on src/points.md
> +	* __Домашние задания__ - 66 баллов. Задания, которые будут выдавать в течение семестра. Для каждой будет отдельный дедлайн, за просрочку которого будет штраф на итоговое количество баллов.
ок, подправил

2023-09-26 16:18 UTC, ErzherzogDX commented on src/points.md
> +	* __Экзамен__ - 20 баллов. Состоит из практической и теоретической части, каждая стоит по 10 баллов. В практической вы за несколько часов пишете задание, которое оценит преподаватель, а в теоретичес
да

2023-09-26 16:19 UTC, ErzherzogDX commented on src/points.md
> +	* __Экзамен__ - 20 баллов. Состоит из практической и теоретической части, каждая стоит по 10 баллов. В практической вы за несколько часов пишете задание, которое оценит преподаватель, а в теоретичес
ок

2023-09-26 16:19 UTC, ErzherzogDX commented on src/points.md
> +	* __Экзамен__ - 20 баллов. Состоит из практической и теоретической части, каждая стоит по 10 баллов. В практической вы за несколько часов пишете задание, которое оценит преподаватель, а в теоретичес
выше описал

2023-09-26 16:24 UTC, ErzherzogDX commented on src/points.md
> +| +      | 01.09, 00:00 | Дедлайн просрочен на 124 дня      | 11.008 |
оке

2023-09-26 16:34 UTC, ErzherzogDX commented on src/points.md
> +| +      | 01.09, 00:00 | Дедлайн просрочен на 124 дня      | 11.008 |
добавил -+ случай

2023-09-26 16:34 UTC, ErzherzogDX commented on src/points.md
> +| +      | 31.04, 23:59 | Дедлайн соблюден, недочетов нет   | 17.600 |
ё)

2023-09-26 16:35 UTC, ErzherzogDX commented on src/points.md
> +По [этой ссылке](https://www.wolframalpha.com/input?i=1*17.6*%280.6+%2B+0.4%2F%281%2B0.35*ceiling%28x%2F3%29%29%29) вы можете сами покрутить эту формулу в WolframAlpha.
ладно

2023-09-26 16:35 UTC, ErzherzogDX commented on src/points.md
> +| +      | 01.09, 00:00 | Дедлайн просрочен на 124 дня      | 11.008 |
есть такой...

2023-09-26 20:26 UTC, ErzherzogDX commented on src/points.md
> +	* __Экзамен__ - 20 баллов. Состоит из практической и теоретической части, каждая стоит по 10 баллов. В практической вы за несколько часов пишете задание, которое оценит преподаватель, а в теоретичес
кк

2023-09-27 09:49 UTC, dedlocc requested changes

2023-09-27 09:49 UTC, dedlocc commented on README.md
> +# C++ Coursezzz
???

2023-09-27 09:49 UTC, dedlocc commented on src/points.md
> +* Без успешной сдачи экзамена вы не можете получить оценку выше FX, то есть:
странная трактовка, но ладно

2023-09-27 10:29 UTC, ErzherzogDX commented on README.md
> +# C++ Coursezzz
случайно залилось

2023-09-27 10:33 UTC, ErzherzogDX commented on src/points.md
> +* Без успешной сдачи экзамена вы не можете получить оценку выше FX, то есть:
сделал "положительную", но добавил ремарку

2023-09-27 10:50 UTC, dedlocc requested changes

2023-09-27 10:50 UTC, dedlocc commented on README.md
> +# C++ Course
потерялся перенос строки в конце

2023-09-27 10:52 UTC, ErzherzogDX commented on README.md
> +# C++ Course
skill issue

2023-09-27 11:01 UTC, dedlocc approved these changes

2023-09-27 11:03 UTC, merged